export const BOOKING_LIST_REQUEST = 'BOOKING_LIST_REQUEST'
export const BOOKING_LIST_SUCCESS = 'BOOKING_LIST_SUCCESS'
export const BOOKING_LIST_FAIL = 'BOOKING_LIST_FAIL'



export const BOOKING_ADD_REQUEST = 'BOOKING_ADD_REQUEST'
export const BOOKING_ADD_SUCCESS = 'BOOKING_ADD_SUCCESS'
export const BOOKING_ADD_FAIL = 'BOOKING_ADD_FAIL'